name: restarter
description: Restarter is a tool that detects file changes and automatically restarts the application.
version: 0.1.1
homepage: https://github.com/xtyxtyx/restarter

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
